import js from '@eslint/js';
import prettier from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';

export default [
    { ignores: ['eslint.config.mjs'] },
    js.configs.recommended,
    prettierConfig,
    {
        plugins: {
            prettier,
        },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                // KubeJS globals
                event: 'readonly',
                global: 'writable',
                Item: 'readonly',
                Ingredient: 'readonly',
                Fluid: 'readonly',
                AABB: 'readonly',
                $BlockPos: 'readonly',
                Vec3: 'readonly',
                UUID: 'readonly',
                Java: 'readonly',
                Platform: 'readonly',
                console: 'readonly',
                Text: 'readonly',
                Component: 'readonly',
                Color: 'readonly',
                JEIEvents: 'readonly',
                ItemEvents: 'readonly',
                FluidEvents: 'readonly',
                BlockEvents: 'readonly',
                EntityEvents: 'readonly',
                PlayerEvents: 'readonly',
                WorldEvents: 'readonly',
                ServerEvents: 'readonly',
                ClientEvents: 'readonly',
                LootJS: 'readonly',
                Block: 'readonly',
                JSONObject: 'readonly',
                FluidIngredientJS: 'readonly',
                LootEntry: 'readonly',
                JavaMath: 'readonly',
                Utils: 'readonly',
                StartupEvents: 'readonly',
                ForgeEvents: 'readonly',
                WorldgenEvents: 'readonly',
                $ServerLevel: 'readonly',
                $Registries: 'readonly',
                $HolderSet: 'readonly',
                $ChunkPos: 'readonly',
                BlockProperties: 'readonly',
                $SectionPos: 'readonly',
                GuiTextureGroup: 'readonly',
                JavaAdapter: 'readonly',
                JsonIO: 'readonly',
                // GTm Globals
                $MultiblockMachineDefinition: 'readonly',
                GTRegistries: 'readonly',
                GTValues: 'readonly',
                GTRecipeCategories: 'readonly',
                CleanroomType: 'readonly',
                GTCEuServerEvents: 'readonly',
                GTMaterials: 'readonly',
                GTMaterialFlags: 'readonly',
                PropertyKey: 'readonly',
                GTCEuStartupEvents: 'readonly',
                GTElements: 'readonly',
                GTMaterialIconSet: 'readonly',
                IngotProperty: 'readonly',
                DustProperty: 'readonly',
                FluidProperty: 'readonly',
                GTFluidStorageKeys: 'readonly',
                GTFluidBuilder: 'readonly',
                BlastProperty: 'readonly',
                $FluidHatchPartMachine: 'readonly',
                $GTMachineModelProperties: 'readonly',
                $CleaningMaintenanceHatchPartMachine: 'readonly',
                RotationState: 'readonly',
                PartAbility: 'readonly',
                GTRecipeTypes: 'readonly',
                GCYMMachines: 'readonly',
                GTRecipeModifiers: 'readonly',
                FactoryBlockPattern: 'readonly',
                Predicates: 'readonly',
                $CoiledMulti: 'readonly',
                GCYMBlocks: 'readonly',
                GTBlocks: 'readonly',
                $SteamMulti: 'readonly',
                $OpticalComputationMachine: 'readonly',
                $LayeredWorkableElectricMultiblockMachine: 'readonly',
                $RelativeDirection: 'readonly',
                $AssemblyLineMulti: 'readonly',
                GTSoundEntries: 'readonly',
                ToolProperty: 'readonly',
                GTToolType: 'readonly',
                $FormattingUtil: 'readonly',
                $FluidPipeProperties: 'readonly',
                GTFluidState: 'readonly',
                $NetworkSwitchMachine: 'readonly',
                GTMachines: 'readonly',
                $TooltipHelper: 'readonly',
                NBTPredicates: 'readonly',
                MultiblockShapeInfo: 'readonly',
                // LDLib globals
                GuiTextures: 'readonly',
                FillDirection: 'readonly',
                WidgetGroup: 'readonly',
                ProgressWidget: 'readonly',
                // Core mod globals
                $StarTAbyssalContainmentMachine: 'readonly',
                $StarTAbyssalContainmentMachine: 'readonly',
                $StarTRecipeModifiers: 'readonly',
                $StartSteamMulti: 'readonly',
                $StarTDraconicInfusionMachine: 'readonly',
                $VacuumChemicalReactorMachine: 'readonly',
                $StarTPartAbility: 'readonly',
                $KomaruFrameMachine: 'readonly',
                $StarTVacuumPumpPredicates: 'readonly',
                $StarTThreadingCapableMachine: 'readonly',
                $StarTThreadingStatBlocks: 'readonly',
                $BoostedPlasmaTurbine: 'readonly',
                $CompoundGeneratorMachine: 'readonly',
                $BulkingMulti: 'readonly',
                $BulkingCoiledMulti: 'readonly',
                $BulkingThreadedMulti: 'readonly',
                // Miscellaneous globals
                Ponder: 'readonly',
                Direction: 'readonly',
                PonderPalette: 'readonly',
                PonderTickingInstruction: 'readonly',
                PonderPointing: 'readonly',
                // Custom globals
                newFactoryBlockPattern: 'writable',
                newFactoryBlockPatternWithDirections: 'writable',
                blockPatternRepeatable: 'writable',
                ponderScenes: 'writable',
                ponderUtils: 'readonly',
                ponderMultis: 'readonly',
                P: 'writable',
                PA: 'writable',
                ICONSETS: 'writable',
                FLAGS: 'writable',
                $: 'writable',
                ULV: 'readonly',
                LV: 'readonly',
                MV: 'readonly',
                HV: 'readonly',
                EV: 'readonly',
                IV: 'readonly',
                LuV: 'readonly',
                ZPM: 'readonly',
                UV: 'readonly',
                UHV: 'readonly',
                UEV: 'readonly',
                UIV: 'readonly',
                UXV: 'readonly',
                OpV: 'readonly',
                MAX: 'readonly',
                T: 'writable',
            },
        },
        rules: {
            indent: 'off',
            'prettier/prettier': 'error',
            camelcase: [
                'error',
                {
                    properties: 'always',
                    ignoreDestructuring: false,
                    ignoreImports: false,
                    allow: ['^\\$?[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'],
                },
            ],
            'id-match': [
                'error',
                '^\\$?([a-z][a-zA-Z0-9]*|[A-Z][A-Z0-9]*(_[A-Z0-9]+)*|\\$[A-Z][a-zA-Z0-9]*|[a-z]|\\$)$',
                {
                    properties: true,
                    onlyDeclarations: true,
                    ignoreDestructuring: true,
                },
            ],
            'no-var': 'error',
            eqeqeq: ['error', 'always'],
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': 'off',
            'no-redeclare': ['error', { builtinGlobals: false }],
            quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: false }],
            'prettier/prettier': [
                'error',
                {
                    endOfLine: 'auto',
                },
            ],
        },
    },
    {
        files: ['kubejs/**/*.js'],
    },
];
