GTCEuStartupEvents.registry('gtceu:recipe_type', (event) => {
    event
        .create('component_synthesis_forge')
        .category('extremely_advanced')
        .setEUIO('in')
        .setMaxIOSize(10, 1, 5, 0)
        .setHasResearchSlot(true)
        .setSound(GTSoundEntries.ASSEMBLER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setMaxTooltips(4);

    event
        .create('component_part_synthesis_forge')
        .category('extremely_advanced')
        .setEUIO('in')
        .setMaxIOSize(6, 1, 2, 0)
        .setHasResearchSlot(true)
        .setSound(GTSoundEntries.ASSEMBLER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setMaxTooltips(4);
});

GTCEuStartupEvents.registry('gtceu:machine', (event) => {
    event
        .create('multithreaded_component_synthesis_forge', 'multiblock')
        .machine((holder) => new $StarTThreadingCapableMachine(holder))
        .rotationState(RotationState.NON_Y_AXIS)
        .tooltips([Text.translate('block.start_core.gap'), Text.translate('block.kubejs.threading.tooltip')])
        .recipeTypes(['component_synthesis_forge', 'component_part_synthesis_forge'])
        .recipeModifiers([
            GTRecipeModifiers.OC_NON_PERFECT_SUBTICK,
            $StarTRecipeModifiers.THREADING_MACHINE,
            GTRecipeModifiers.BATCH_MODE,
        ])
        .appearanceBlock(() => Block.getBlock('kubejs:nyanium_machine_casing'))
        .pattern((definition) =>
            newFactoryBlockPattern([
                '           BCBBBCB           |            C   C            |            C   C            |           BCBBBCB           |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             ',
                '         BBBBBBBBBBB         |           DEEEEED           |           DEEEEED           |         BBBFFFFFBBB         |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             ',
                '       BBBBBBBBBBBBBBB       |         DDGGGGGGGDD         |         DDGG222GGDD         |       BBBBBF   FBBBBB       |                             |                             |                             |             AAA             |            A   A            |            A   A            |            A   A            |             AAA             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |             AAA             |            A   A            |            A   A            |            A   A            |             AAA             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |           BBBBBBB           ',
                '     BBBBBBBBBBBBBBBBBBB     |       DDGGGGGGGGGGGDD       |       DDGGGG222GGGGDD       |     BBBCCCBF   FBCCCBBB     |                             |                             |                             |            A   A            |             DDD             |             DJD             |             DDD             |            A   A            |                             |                             |                             |                             |                             |             KKK             |           IIKLKII           |             KKK             |                             |                             |                             |                             |                             |            A   A            |             DDD             |             DJD             |             DDD             |            A   A            |                             |                             |                             |                             |        BBB       BBB        |                             |                             |                             |                             |                             |         BBBCCCCCBBB         ',
                '    CBBBBBBBBBBBBBBBBBBBC    |    CDDGGGGGEEEEEGGGGGDDC    |    CDDGGGGGEEEEEGGGGGDDC    |    CBBBCLCBFFFFFBCLCBBBC    |          I       I          |           I     I           |            I   I            |            AI IA            |             DLD             |           KKKMKKK           |             DLD             |            AI IA            |            I   I            |           I     I           |          I       I          |                             |                             |                             |         II       II         |                             |                             |                             |          I       I          |           I     I           |            I   I            |            AI IA            |             DLD             |           KKKMKKK           |             DLD             |            AI IA            |            I   I            |           I     I           |                             |                             |      BBBBBB     BBBBBB      |                             |                             |                             |           I     I           |            I   I            |        BBBBCLCLCBBBB        ',
                '   BBBBBBBBBCBBBCBBBBBBBBB   |    DGGGGGDDC   CDDGGGGGD    |    DGGGGGDDC   CDDGGGGGD    |   BBBBBCCCBCBBBCBCCCBBBBB   |                             |                             |                             |            A   A            |             DDD             |        KKK  DMD  KKK        |             DDD             |            A   A            |                             |                             |                             |         I         I         |                    I        |                             |        I           I        |                             |        I           I        |         I         I         |                             |                             |                             |            A   A            |             DDD             |        KKK  DMD  KKK        |             DDD             |            A   A            |                             |          I       I          |         I         I         |        I           I        |     BCCCBBB     BBBCCCB     |        I           I        |         I         I         |          I       I          |                             |                             |        BBBBCCCCCBBBB        ',
                '   BBBBBBBBBBBBBBBBBBBBBBB   |    DGGGGD         DGGGGD    |    DGGGGD         DGGGGD    |   BBBBBBBBB     BBBBBBBBB   |                             |                             |                             |             AAA             |            ABFBA            |      KK    AFFFA    KK      |            ABFBA            |             AAA             |                             |                             |                             |                             |        I                    |      KK             KK      |      LK             KL      |      KK             KK      |                             |                             |                             |                             |                             |             AAA             |            ABFBA            |      KK    AFFFA    KK      |            ABFBA            |             AAA             |                             |                             |                             |                             |    BCCLCBBB     BBBCLCCB    |                             |                             |                             |                             |                             |        BBBBBBBBBBBBB        ',
                '  BBBBBBBBIIIIBIIIIBBBBBBBB  |   DGGGGD           DGGGGD   |   DGGGGD           DGGGGD   |  BBBBBBBB         BBBBBBBB  |                             |                             |                             |                             |              L              |      K      LPL      K      |              L              |                             |                             |                             |                             |                             |                             |      KK             KK      |      KL             LK      |      KK             KK      |                             |                             |                             |                             |                             |                             |              L              |      K      LPL      K      |              L              |                             |                             |                             |                             |                             |    BCLCCBB       BBCCLCB    |                             |                             |                             |                             |                             |         BBB     BBB         ',
                '  BBBBBBCI   IBI   ICBBBBBB  |   DGGGDC           CDGGGD   |   DGGGDC           CDGGGD   |  BCCCBBC           CBBCCCB  |                             |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |                             |                             |                             |     I                I      |                             |     I                 I     |                             |     I                 I     |                             |                             |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |                             |                             |     I                 I     |   BBCCCBB         BBCCCBB   |     I                 I     |                             |                             |                             |                             |    BBB               BBB    ',
                ' BBBBBBBI    IBI    IBBBBBBB |  DGGGD               DGGGD  |  DGGGD               DGGGD  | BBCLCBB             BBCLCBB |                             |                             |                             |                             |                             |     K        H        K     |                             |                             |                             |                             |                             |     I                 I     |                             |                             |    I                   I    |                             |                             |     I                 I     |                             |                             |                             |                             |                             |     K        H        K     |                             |                             |                             |                             |     I                 I     |                             |   BBBBBB           BBBBBB   |                             |     I                 I     |                             |                             |                             |   BBBBB             BBBBB   ',
                ' BBBBBBI    IIBII    IBBBBBB |  DGGD                 DGGD  |  DGGD                 DGGD  | BBCCCB               BCCCBB |    I                   I    |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |                             |    I                   I    |                             |                             |                             |    I                   I    |                             |                             |                             |    I                   I    |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |     I                 I     |                             |                             |   BBBBB             BBBBB   |                             |                             |     I                 I     |                             |                             |   BBBBB             BBBBB   ',
                'BBBBBBBI   IBBBBBI   IBBBBBBB| DGGGD                 DGGGD | DGGGD                 DGGGD |BBBBBBB               BBBBBBB|                             |    I                   I    |                             |                             |              L              |    K        LPL        K    |              L              |                             |                             |    I                   I    |                             |                             |                             |                             |   I                     I   |                             |                             |                             |                             |    I                   I    |                             |                             |              L              |    K        LPL        K    |              L              |                             |                             |    I                   I    |                             |                             |    BBB               BBB    |                             |                             |                             |    I                   I    |                             |  BBBBBB             BBBBBB  ',
                'CBBBBCBI  IBCBBBCBI  IBCBBBBC|CEGGEC      CAAAC      CEGGEC|CEGGEC                 CEGGEC|CFFFFC                 CFFFFC|                             |                             |    I                   I    |   AAA       AAA      AAAA   |  A   A     ABFBA     A   A  |  A K A     AFFFA     A K A  |  A   A     ABFBA     A   A  |   AAA       AAA       AAA   |    I                   I    |                             |                             |                             |                             |              D              |   I          Q          I   |              D              |                             |                             |                             |                             |    I                   I    |   AAA       AAA      AAAA   |  A   A     ABFBA     A   A  |  A K A     AFFFA     A K A  |  A   A     ABFBA     A   A  |   AAA       AAA       AAA   |    I                   I    |                             |                             |                             |                             |             AAA             |            A   A            |            A   A            |            A   A            |    I        AAA        I    |  BCCCB               BCCCB  ',
                'BBBBBBBIIIIBBBBBBBIIIIBBBBBBB| EGGE       ABFBA       EGGE | E22E         L         E22E |BF  FB        L        BF  FB|                             |              L              |              L              |  A I A     ABFBA     A I A  |   DDDB     BPHPB     BDDD   |   DKDFLL LLFHHHFLL LLFDKD   |   DDDB     BPHPB     BDDD   |  A I A     ABFBA     A I A  |              L              |              L              |                             |              L              |              L              |   K         DPD         K   |   K         DPD         K   |   K         DPD         K   |              L              |              L              |                             |              L              |              L              |  A I A     ABFBA     A I A  |   DDDB     BPHPB     BDDD   |   DKDFLL LLFHHHFLL LLFDKD   |   DDDB     BPHPB     BDDD   |  A I A     ABFBA     A I A  |              L              |              L              |                             |              L              |              L              |            ABFBA            |             000             |             000             |             000             |            A   A            |  BCLCB               BCLCB  ',
                'BBBBBBBBBBBBBBBBBBBBBBBBBBBBB| EGGE       AFFFA       EGGE | E22E        LPL        E22E |BF  FB       LPL       BF  FB|              H              |             LPL             |             LPL             |  A   A     AFFFA     A   A  |   DLDFLL LLFHHHFLL LLFDLD   |   JMMFPPHPPFHHHFPPHPPFMMJ   |   DLDFLL LLFHHHFLL LLFDLD   |  A   A     AFFFA     A   A  |             LPL             |             LPL             |              H              |             LPL             |             LPL             |   K        DPHPD        K   |   L        DPHPD        L   |   K        DPHPD        K   |             LPL             |             LPL             |              H              |             LPL             |             LPL             |  A   A     AFFFA     A   A  |   DLDFLL LLFHHHFLL LLFDLD   |   JMMFPPHPPFHHHFPPHPPFMMJ   |   DLDFLL LLFHHHFLL LLFDLD   |  A   A     AFFFA     A   A  |             LPL             |             LPL             |              H              |             LPL             |             LPL             |            AFFFA            |             0M0             |             0M0             |             000             |            A   A            |  BCCCB               BCCCB  ',
                'BBBBBBBIIIIBBBBBBBIIIIBBBBBBB| EGGE       ABFBA       EGGE | E22E         L         E22E |BF  FB        L        BF  FB|                             |              L              |              L              |  A I A     ABFBA     A I A  |   DDDB     BPHPB     BDDD   |   DKDFLL LLFHHHFLL LLFDKD   |   DDDB     BPHPB     BDDD   |  A I A     ABFBA     A I A  |              L              |              L              |                             |              L              |              L              |   K         DPD         K   |   K         DPD         K   |   K         DPD         K   |              L              |              L              |                             |              L              |              L              |  A I A     ABFBA     A I A  |   DDDB     BPHPB     BDDD   |   DKDFLL LLFHHHFLL LLFDKD   |   DDDB     BPHPB     BDDD   |  A I A     ABFBA     A I A  |              L              |              L              |                             |              L              |              L              |            ABFBA            |             000             |             000             |             000             |            A   A            |  BCLCB               BCLCB  ',
                'CBBBBCBI  IBCBBBCBI  IBCBBBBC|CEGGEC      CAAAC      CEGGEC|CEGGEC                 CEGGEC|CFFFFC                 CFFFFC|                             |                             |    I                   I    |   AAA       AAA       AAA   |  A   A     ABFBA     A   A  |  A K A     AFFFA     A K A  |  A   A     ABFBA     A   A  |   AAA       AAA       AAA   |    I                   I    |                             |                             |                             |                             |              D              |   I          @          I   |              D              |                             |                             |                             |                             |    I                   I    |   AAA       AAA       AAA   |  A   A     ABFBA     A   A  |  A K A     AFFFA     A K A  |  A   A     ABFBA     A   A  |   AAA       AAA       AAA   |    I                   I    |                             |                             |                             |                             |             AAA             |            A   A            |            A   A            |            A   A            |    I        AAA        I    |  BCCCB               BCCCB  ',
                'BBBBBBBI   IBBBBBI   IBBBBBBB| DGGGD                 DGGGD | DGGGD                 DGGGD |BBBBBBB               BBBBBBB|                             |    I                   I    |                             |                             |              L              |    K        LPL        K    |              L              |                             |                             |    I                   I    |                             |                             |                             |                             |   I                     I   |                             |                             |                             |                             |    I                   I    |                             |                             |              L              |    K        LPL        K    |              L              |                             |                             |    I                   I    |                             |                             |    BBB               BBB    |                             |                             |                             |    I                   I    |                             |  BBBBBB             BBBBBB  ',
                ' BBBBBBI    IIBII    IBBBBBB |  DGGD                 DGGD  |  DGGD                 DGGD  | BBCCCB               BCCCBB |    I                   I    |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |                             |    I                   I    |                             |                             |                             |    I                   I    |                             |                             |                             |    I                   I    |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |     I                 I     |                             |                             |   BBBBB             BBBBB   |                             |                             |     I                 I     |                             |                             |   BBBBB             BBBBB   ',
                ' BBBBBBBI    IBI    IBBBBBBB |  DGGGD               DGGGD  |  DGGGD               DGGGD  | BBCLCBB             BBCLCBB |                             |                             |                             |                             |                             |     K        H        K     |                             |                             |                             |                             |                             |     I                 I     |                             |                             |    I                   I    |                             |                             |     I                 I     |                             |                             |                             |                             |                             |     K        H        K     |                             |                             |                             |                             |     I                 I     |                             |   BBBBBB           BBBBBB   |                             |     I                 I     |                             |                             |                             |   BBBBB             BBBBB   ',
                '  BBBBBBCI   IBI   ICBBBBBB  |   DGGGDC           CDGGGD   |   DGGGDC           CDGGGD   |  BCCCBBC           CBBCCCB  |                             |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |                             |                             |                             |      I                I     |                             |     I                 I     |                             |     I                 I     |                             |                             |                             |                             |                             |              L              |     K       LPL       K     |              L              |                             |                             |                             |                             |     I                 I     |   BBCCCBB         BBCCCBB   |     I                 I     |                             |                             |                             |                             |    BBB               BBB    ',
                '  BBBBBBBBIIIIBIIIIBBBBBBBB  |   DGGGGD           DGGGGD   |   DGGGGD           DGGGGD   |  BBBBBBBB         BBBBBBBB  |                             |                             |                             |                             |              L              |      K      LPL      K      |              L              |                             |                             |                             |                             |                             |                             |      KK             KK      |      KL             LK      |      KK             KK      |                             |                             |                             |                             |                             |                             |              L              |      K      LPL      K      |              L              |                             |                             |                             |                             |                             |    BCLCCBB       BBCCLCB    |                             |                             |                             |                             |                             |         BBB     BBB         ',
                '   BBBBBBBBBBBBBBBBBBBBBBB   |    DGGGGD         DGGGGD    |    DGGGGD         DGGGGD    |   BBBBBBBBB     BBBBBBBBB   |                             |                             |                             |             AAA             |            ABFBA            |      KK    AFFFA    KK      |            ABFBA            |             AAA             |                             |                             |                             |                             |                    I        |      KK             KK      |      LK             KL      |      KK             KK      |                             |                             |                             |                             |                             |             AAA             |            ABFBA            |      KK    AFFFA    KK      |            ABFBA            |             AAA             |                             |                             |                             |                             |    BCCLCBBB     BBBCLCCB    |                             |                             |                             |                             |                             |        BBBBBBBBBBBBB        ',
                '   BBBBBBBBBCBBBCBBBBBBBBB   |    DGGGGGDDC   CDDGGGGGD    |    DGGGGGDDC   CDDGGGGGD    |   BBBBBCCCBCBBBCBCCCBBBBB   |                             |                             |                             |            A   A            |             DDD             |        KKK  DMD  KKK        |             DDD             |            A   A            |                             |                             |                             |         I         I         |        I                    |                             |        I           I        |                             |        I           I        |         I         I         |                             |                             |                             |            A   A            |             DDD             |        KKK  DMD  KKK        |             DDD             |            A   A            |                             |          I       I          |         I         I         |        I           I        |     BCCCBBB     BBBCCCB     |        I           I        |         I         I         |          I       I          |                             |                             |        BBBBCCCCCBBBB        ',
                '    CBBBBBBBBBBBBBBBBBBBC    |    CDDGGGGGEEEEEGGGGGDDC    |    CDDGGGGGEEEEEGGGGGDDC    |    CBBBCLCBFFFFFBCLCBBBC    |          I       I          |           I     I           |            I   I            |            AI IA            |             DLD             |           KKKMKKK           |             DLD             |            AI IA            |            I   I            |           I     I           |          I       I          |                             |                             |                             |         II       II         |                             |                             |                             |          I       I          |           I     I           |            I   I            |            AI IA            |             DLD             |           KKKMKKK           |             DLD             |            AI IA            |            I   I            |           I     I           |                             |                             |      BBBBBB     BBBBBB      |                             |                             |                             |           I     I           |            I   I            |        BBBBCLCLCBBBB        ',
                '     BBBBBBBBBBBBBBBBBBB     |       DDGGGGGGGGGGGDD       |       DDGGGG222GGGGDD       |     BBBCCCBF   FBCCCBBB     |                             |                             |                             |            A   A            |             DDD             |             DJD             |             DDD             |            A   A            |                             |                             |                             |                             |                             |             KKK             |           IIKLKII           |             KKK             |                             |                             |                             |                             |                             |            A   A            |             DDD             |             DJD             |             DDD             |            A   A            |                             |                             |                             |                             |        BBB       BBB        |                             |                             |                             |                             |                             |         BBBCCCCCBBB         ',
                '       BBBBBBBBBBBBBBB       |         DDGGGGGGGDD         |         DDGG222GGDD         |       BBBBBF   FBBBBB       |                             |                             |                             |             AAA             |            A   A            |            A   A            |            A   A            |             AAA             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |             AAA             |            A   A            |            A   A            |            A   A            |             AAA             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |           BBBBBBB           ',
                '         BBBBBBBBBBB         |           DEEEEED           |           DEEEEED           |         BBBFFFFFBBB         |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             ',
                '           BCBBBCB           |            C   C            |            C   C            |           BCBBBCB           |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             |                             ',
            ])
                .whereDict({
                    A: P.gtBlock('sturdy_machine_casing'),
                    ' ': P.any(),
                    B: P.kjsBlock('advanced_assembly_casing'),
                    C: P.kjsBlock('draco_assembly_grating'),
                    D: P.kjsBlock('nyanium_machine_casing'),
                    E: P.kjsBlock('nyanium_firebox_casing'),
                    F: P.coreBlock('fusion_casing_mk4'),
                    G: P.kjsBlock('superdense_assembly_machine_casing'),
                    H: P.coreBlock('advanced_fusion_coil'),
                    I: P.kjsBlock('draco_resilient_fusion_glass'),
                    J: P.gtBlock('uiv_rotor_holder'),
                    K: P.gtBlock('palladium_substation'),
                    L: P.kjsBlock('draco_ware_casing'),
                    M: P.kjsBlock('nyanium_pipe_casing'),
                    P: P.kjsBlock('superdense_assembly_control_casing'),
                    Q: P.coreBlock('threading_controller'),
                    2: P.threadingBlocks(),
                    0: P.anyOf([
                        P.kjsBlock('nyanium_machine_casing'),
                        P.ability(PA.fluidIn, { view: 1 }),
                        P.ability(PA.itemIn, { view: 1 }),
                        P.ability(PA.itemOut, { view: 1 }),
                        P.ability(PA.optIn, { exact: 1 }),
                        P.ability(PA.euIn, { max: 2, view: 1 }),
                        P.gtBlock('uhv_stabilization_module', { exact: 1 }),
                    ]),
                    '@': P.controller(definition),
                })
                .build()
        )
        .workableCasingModel('kubejs:block/casings/nyanium/casing', 'gtceu:block/machines/assembler');
});
