GTCEuStartupEvents.registry('gtceu:machine', (event) => {
    event
        .create('ultimate_ebf', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .machine((holder) => new $BulkingCoiledMulti(holder))
        .recipeType('electric_blast_furnace')
        .recipeModifiers([
            GTRecipeModifiers.PARALLEL_HATCH,
            GTRecipeModifiers.EBF_OVERCLOCK,
            $StarTRecipeModifiers.THROUGHPUT_BOOSTING,
            $StarTRecipeModifiers.BULKING,
            GTRecipeModifiers.BATCH_MODE,
        ])
        .appearanceBlock(() => Block.getBlock('kubejs:extreme_temperature_smelting_casing'))
        .pattern((definition) =>
            newFactoryBlockPattern([
                '     BBBBBBBBBBB     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BBBBBCCCCCCCCCBBBBB |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BCCCCCCCDDDCCCCCCCB |       BB E BB       |       BBEEEBB       |       BB E BB       |       BB E BB       |       BBBBBBB       |       B     B       |       BBBBBBB       |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BCCCDDCCCDCCCDDCCCB |   BBEEBBBBBBBEEBB   |   BB  BB   BB  BB   |    B  BB   BB  B    |    B  BB   BB  B    |    B  BBBBBBB  B    |   BB  BFGHGFB  BB   |   BBEEBCCCCCBEEBB   |        CCCCC        |          E          |          E          |          E          |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BCCCCDCCCGCCCDCCCCB |   BBBBBCCCCCBBBBB   |   BB  BCCCCCB  BB   |   BB  BCCICCB  BB   |   BB  BCCCCCB  BB   |   BBBBBCCCCCBBBBB   |   BB  BCCCCCB  BB   |   BBBBBCCGCCBBBBB   |    BB ECDDDCE BB    |    BB E     E BB    |     B E     E B     |     B ECCCCCE B     |     B    E    B     |    BB    E    BB    |    BB    E    BB    |          E          |          E          |          E          |                     |                     |    BB  CCCCC  BB    |    BB         BB    |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                'BBCDCCGCCCGCCCGCCDCBB|   EBCCCCCCCCCCCBE   |     DDCCCCCCCDD     |     DDCCCGCCCDD     |     DDCCCCCCCDD     |    BCCCCCCCCCCCB    |     HFCCCCCCCFH     |   EBBCCCCGCCCCBBE   |    BBCCCJGJCCCBB    |    BB    G    BB    |    BB    G    BB    |    BBCCCCCCCCCBB    |    BB  E   E  BB    |    BB  E   E  BB    |    BBCCCCCCCCCBB    |     E         E     |     E         E     |     E    E    E     |     E         E     |     E         E     |    BBCCCCCCCCCBB    |    BB   EEE   BB    |          E          |          E          |          E          |          E          |        EEEEE        |                     |                     |                     |                     |                     |        BBBBB        ',
                'BCCDDGGGGGGGGGGGDDCCB|   EBCCCCCCCCCCCBE   |     DCCCCCCCCCD     |     DGGGGGGGGGD     |     DGDGFGFGDGD     |    BCGGJJGJJGGCB    |     FGFJHGHJFGF     |   EBCGGGGHGGGGCBE   |     CCFJHGHJFCC     |      BBHFGFHBB      |      BBGKGKGBB      |     CBBJJJJJBBC     |      BB     BB      |      BBE   EBB      |     CBBCCCCCBBC     |      BB  E  BB      |      E   E   E      |        EEEEE        |      E   E   E      |      BB  E  BB      |     CBBCCCCCBBC     |      EEE   EEE      |      E       E      |      E       E      |      E       E      |      EE     EE      |      EEECCCEEE      |          E          |          E          |          E          |          E          |          E          |      BBBCCCBBB      ',
                'BCCCCCGCCCGCCCGCCCCCB|  BBBCCCCCCCCCCCBBB  |  BBBCCCCCCCCCCCBBB  |  BBBCGDGHGHGDGCBBB  |  BBBCD       DCBBB  |  BBBCG       GCBBB  |  BBBCF       FCBBB  |  BBBCG       GCBBB  |    ECF       FCE    |    E BF     FB E    |    E BG  G  GB E    |    ECBJDDDDDJBCE    |      B       B      |      B E   E B      |     CBBDDDDDBBC     |      BBE   EBB      |       BEJJJEB       |       BEJGJEB       |       BEJJJEB       |      BBE   EBB      |     CBCCCGCCCBC     |      E   G   E      |          G          |          G          |          G          |      E   G   E      |      ECCCCCCCE      |       E  G  E       |       E  G  E       |       EEEGEEE       |       E  G  E       |       E  G  E       |      BCCCGCCCB      ',
                'BCCCCCGCCCGCCCGCCCCCB|  BBCCCCCCCCCCCCCBB  |  BBCCCCCCCCCCCCCBB  |  BBCCGGJJGJJGGCCBB  |  BBCCG       GCCBB  |  BBCCJ       JCCBB  |   FCCJ       JCCF   |  BCCCG  HGH  GCCCB  |   CCCJ  JGJ  JCCC   |      H  JGJ  H      |      G  JGJ  G      |    CCJDDHGHDDJCC    |     E   FGF   E     |     EEEEHGHEEEE     |     CCDDGGGDDCC     |       E HGH E       |       E FGF E       |      EE GGG EE      |       E FGF E       |       E HGH E       |    CCCCGGGGGCCCC    |      E FHGHF E      |        JJJJJ        |        GJJJG        |        JJJJJ        |        FHGHF        |     EECGGGGGCEE     |        FHGHF        |        GJJJG        |       EHJJJHE       |        GJJJG        |        FHGHF        |     BBCGGGGGCBB     ',
                'BCDCCCGCCCGCCCGCCCDCB|   BCCCCCCCCCCCCCB   |  E CCCCCCCCCCCCC E  |    CCGHJHGHJHGCC    |    CCF       FCC    |  BBCCJ       JCCBB  |   GCCH       HCCG   |  BCCCG H G H GCCCB  |   CDJH J   J HJDC   |      F J   J F      |      K J   J K      |    CCJDH   HDJCC    |        F   F        |        H   H        |     CCDG G GDCC     |        H   H        |       JF   FJ       |      EJG   GJE      |       JF   FJ       |        H   H        |    CCCCG G GCCCC    |     E  H   H  E     |        J   J        |        J   J        |        J   J        |        H   H        |     ECCG G GCCE     |        H   H        |        J   J        |       EJ   JE       |        J   J        |        H   H        |     BCCGMCMGCCB     ',
                'BCDDGGGGGGGGGGGGGDDCB|  EBCCCCCCGCCCCCCBE  |  E CCCCCCGCCCCCC E  |  E IGGGGGGGGGGGI E  |  E CCG   G   GCC E  |  BBCCG   G   GCCBB  |   HCCG   G   GCCH   |  BCGGH GGGGG HGGCB  |   CDGG G   G GGDC   |   E GG G   G GG E   |   E GGGG   GGGG E   |   ECCJDG   GDJCCE   |    E   G   G   E    |    E   G   G   E    |    ECCDGGGGGDCCE    |    E E G G G E E    |    E EJG G GJE E    |    EEEGG G GGEEE    |      EJG G GJE      |      E G G G E      |    CCCGGGGGGGCCC    |     E GG   GG E     |     E GJ   JG E     |     E GJ   JG E     |     E GJ   JG E     |     E GG   GG E     |     ECCGGGGGCCE     |      EGG   GGE      |      EGJ   JGE      |      EGJ   JGE      |      EGJ   JGE      |      EGG   GGE      |     BCGGCCCGGCB     ',
                'BCDCCCGCCCGCCCGCCCDCB|   BCCCCCCCCCCCCCB   |  E CCCCCCCCCCCCC E  |    CCGHJHGHJHGCC    |    CCF       FCC    |  BBCCJ       JCCBB  |   GCCH       HCCG   |  BCCCG H G H GCCCB  |   CDJH J   J HJDC   |      F J   J F      |      K J   J K      |    CCJDH   HDJCC    |        F   F        |        H   H        |     CCDG G GDCC     |        H   H        |       JF   FJ       |      EJG   GJE      |       JF   FJ       |        H   H        |    CCCCG G GCCCC    |     E  H   H  E     |        J   J        |        J   J        |        J   J        |        H   H        |     ECCG G GCCE     |        H   H        |        J   J        |       EJ   JE       |        J   J        |        H   H        |     BCCGMCMGCCB     ',
                'BCCCCCGCCCGCCCGCCCCCB|  BBCCCCCCCCCCCCCBB  |  BBCCCCCCCCCCCCCBB  |  BBCCGGJJGJJGGCCBB  |  BBCCG       GCCBB  |  BBCCJ       JCCBB  |   FCCJ       JCCF   |  BCCCG  HGH  GCCCB  |   CCCJ  JGJ  JCCC   |      H  JGJ  H      |      G  JGJ  G      |    CCJDDHGHDDJCC    |     E   FGF   E     |     EEEEHGHEEEE     |     CCDDGGGDDCC     |       E HGH E       |       E FGF E       |      EE GGG EE      |       E FGF E       |       E HGH E       |    CCCCGGGGGCCCC    |      E FHGHF E      |        JJJJJ        |        GJJJG        |        JJJJJ        |        FHGHF        |     EECGGGGGCEE     |        FHGHF        |        GJJJG        |       EHJJJHE       |        GJJJG        |        FHGHF        |     BBCGGGGGCBB     ',
                'BCCCCCGCCCGCCCGCCCCCB|  BBBCCCCCCCCCCCBBB  |  BBBCCCCCCCCCCCBBB  |  BBBCGDGHGHGDGCBBB  |  BBBCD       DCBBB  |  BBBCG       GCBBB  |  BBBCF       FCBBB  |  BBBCG       GCBBB  |    ECF       FCE    |    E BF     FB E    |    E BG  G  GB E    |    ECBJDDDDDJBCE    |      B       B      |      B E   E B      |     CBBDDDDDBBC     |      BBE   EBB      |       BEJJJEB       |       BEJGJEB       |       BEJJJEB       |      BBE   EBB      |     CBCCCGCCCBC     |      E   G   E      |          G          |          G          |          G          |      E   G   E      |      ECCCCCCCE      |       E  G  E       |       E  G  E       |       EEEGEEE       |       E  G  E       |       E  G  E       |      BCCCGCCCB      ',
                'BCCDDGGGGGGGGGGGDDCCB|   EBCCCCCCCCCCCBE   |     DCCCCCCCCCD     |     DGGGGGGGGGD     |     DGDGFGFGDGD     |    BCGGJJGJJGGCB    |     FGFJHGHJFGF     |   EBCGGGGHGGGGCBE   |     CCFJHGHJFCC     |      BBHFGFHBB      |      BBGKGKGBB      |     CBBJJJJJBBC     |      BB     BB      |      BBE   EBB      |     CBBCCCCCBBC     |      BB  E  BB      |      E   E   E      |        EEEEE        |      E   E   E      |      BB  E  BB      |     CBBCCCCCBBC     |      EEE   EEE      |      E       E      |      E       E      |      E       E      |      EE     EE      |      EEECCCEEE      |          E          |          E          |          E          |          E          |          E          |      BBBCCCBBB      ',
                'BBCDCCGCCCGCCCGCCDCBB|   EBCCCCCCCCCCCBE   |     DDCCCCCCCDD     |     DDCCCGCCCDD     |     DDCCCCCCCDD     |    BCCCCCCCCCCCB    |     HFCCCCCCCFH     |   EBBCCCCGCCCCBBE   |    BBCCCJGJCCCBB    |    BB    G    BB    |    BB    G    BB    |    BBCCCCCCCCCBB    |    BB  E   E  BB    |    BB  E   E  BB    |    BBCCCCCCCCCBB    |     E         E     |     E         E     |     E    E    E     |     E         E     |     E         E     |    BBCCCCCCCCCBB    |    BB   EEE   BB    |          E          |          E          |          E          |          E          |        EEEEE        |                     |                     |                     |                     |                     |        BBBBB        ',
                ' BCCCCDCCCGCCCDCCCCB |   BBBBBCCCCCBBBBB   |   BB  BCCCCCB  BB   |   BB  BCCICCB  BB   |   BB  BCCCCCB  BB   |   BBBBBCCCCCBBBBB   |   BB  BCCCCCB  BB   |   BBBBBCCGCCBBBBB   |    BB ECDDDCE BB    |    BB E     E BB    |     B E     E B     |     B ECCCCCE B     |     B    E    B     |    BB    E    BB    |    BB    E    BB    |          E          |          E          |          E          |                     |                     |    BB  CCCCC  BB    |    BB         BB    |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BCCCDDCCCDCCCDDCCCB |   BBEEBBBBBBBEEBB   |   BB  BB   BB  BB   |    B  BB   BB  B    |    B  BB   BB  B    |    B  BBBBBBB  B    |   BB  BFGHGFB  BB   |   BBEEBCCCCCBEEBB   |        CC@CC        |          E          |          E          |          E          |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BCCCCCCCDDDCCCCCCCB |       BB E BB       |       BBEEEBB       |       BB E BB       |       BB E BB       |       BBBBBBB       |       B     B       |       BBBBBBB       |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                ' BBBBBCCCCCCCCCBBBBB |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
                '     BBBBBBBBBBB     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     |                     ',
            ])
                .whereDict({
                    M: P.ability(PA.muffler),
                    ' ': P.any(),
                    B: P.kjsBlock('reinforced_brimstone_casing'),
                    C: P.anyOf([
                        P.kjsBlock('extreme_temperature_smelting_casing'),
                        P.ability(PA.itemIn, { max: 8, view: 1 }),
                        P.ability(PA.itemOut, { max: 8, view: 1 }),
                        P.ability(PA.fluidIn, { max: 8, view: 1 }),
                        P.ability(PA.fluidOut, { max: 8, view: 1 }),
                        P.ability(PA.euIn, { max: 2, view: 1 }),
                        P.ability(PA.maintenance, { exact: 1 }),
                        P.ability(PA.parallelHatch, { max: 1 }),
                    ]),
                    D: P.gtBlock('heat_vent'),
                    E: P.gtBlock('abyssal_alloy_frame'),
                    F: P.kjsBlock('nyanium_firebox_casing'),
                    G: P.kjsBlock('nyanium_pipe_casing'),
                    H: P.kjsBlock('nyanium_engine_intake_casing'),
                    I: P.gtBlock('uev_rotor_holder'),
                    J: P.heatingCoil(),
                    K: P.kjsBlock('nyanium_machine_casing'),
                    '@': P.controller(definition),
                })
                .build()
        )
        .workableCasingModel(
            'kubejs:block/casings/nether_multis/extreme_temperature_smelting_casing',
            'gtceu:block/multiblock/gcym/mega_blast_furnace'
        )
        .additionalDisplay(global.coilMachineTempDisplay);
});
